steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}', './django-backend']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploying image to Cloud Run'
  args:
    - run
    - deploy
    - $_CLOUD_RUN_SERVICE
    - --image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}
    - --port=$_APP_PORT
    - --region=us-central1
    - --platform=managed
    - --allow-unauthenticated
    # Ambiente - logs
    - "--set-env-vars=APP_ENV=${_APP_ENV}"
    # Base de Datos
    - "--set-env-vars=DB_DIALECT=${_DB_ENGINE}"
    - "--set-env-vars=DB_SOCKET=${_DB_SOCKET}"
    - "--set-env-vars=DB_DATABASE=${_DB_DATABASE}"
    - "--set-env-vars=DB_USERNAME=${_DB_USERNAME}"
    - "--set-env-vars=DB_PASSWORD=${_DB_PASSWORD}"
    # Memoria - Instancias
    - --memory=$_MEMORY_LIMIT
    - --min-instances=$_INSTANCES_MIN
    - --max-instances=$_INSTANCES_MAX
timeout: "240s"
